twig:
    
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    
    form_themes: ['tailwind_2_layout.html.twig']
    globals:
        live_component_renderer: '@ux.live_component.twig.component_runtime'
        
    paths:
        '%kernel.project_dir%/vendor/symfony/ux-live-component/templates': LiveComponent
    

when@test:
    twig:
        strict_variables: true
