services:
  php:
    image: symfony-php-1
    build:
      context: .
      dockerfile: Dockerfile
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    container_name: symfony-php-1
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app:cached
      - php_npm:/app/.npm
    #  - php_node_modules:/app/node_modules
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://symfony:symfony@database:3306/symfony?serverVersion=8.0&charset=utf8mb4
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    container_name: symfony-mysql-1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  nginx:
    image: nginx:latest
    container_name: symfony-nginx-1
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php

  node:
    image: node:18
    container_name: symfony-node-1
    user: "1000:1000"
    working_dir: /app
    environment:
      NPM_CONFIG_PREFIX: /home/node/.npm-global
      NPM_CONFIG_CACHE: /home/node/.npm-cache
    volumes:
      - .:/app:cached
      - node_data:/home/node
      - public_build:/app/public/build
    command: ["tail", "-f", "/dev/null"]
    networks:
      - default

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db_data:
  php_npm:
  php_node_modules:
  node_modules:
  public_build:
  node_data: {}
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
